name: Build

on: 
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

    branches:
      - main
      - develop

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Use .NET 8 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Build
      if: runner.os != 'Windows'
      run: |
        chmod +x ./build.sh
        ./build.sh
      env:
        CI: true

    - name: Build
      if: runner.os == 'Windows'
      run: ./build.cmd
      env:
        CI: true
