name: Build master

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Use .NET 6 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.x'
    # Not specifying a version will attempt to install via global.json
    - name: Use .NET Core global.json
      uses: actions/setup-dotnet@v1

    - name: Build
      if: runner.os != 'Windows'
      run: |
        chmod +x ./build.sh
        ./build.sh
      env:
        CI: true
    - name: Build
      if: runner.os == 'Windows'
      run: ./build.cmd
      env:
        CI: true
